export const styles = {
  card: {
    width: 1,
    height: '100%',
    borderRadius: 2.5,
    border: '1px solid',
    borderColor: 'divider',
    boxShadow: 'none',
    transition: (theme) =>
      theme.transitions.create(['box-shadow', 'border-color', 'opacity'], { duration: 220 }),
    '&:hover': {
      borderColor: 'action.hover',
      boxShadow: (theme) => theme.shadows[2],
    },
  },
  cardBusy: {
    opacity: 0.88,
  },
  previewClickable: {
    cursor: 'pointer',
    borderRadius: 1,
    m: -0.5,
    p: 0.5,
    outlineOffset: 2,
    transition: (theme) => theme.transitions.create(['box-shadow'], { duration: 180 }),
    '&:focus-visible': {
      outline: '2px solid',
      outlineColor: 'primary.main',
    },
  },
  cardContent: { p: 1.5 },
  categoryCaptionOuter: { opacity: 0.84 },
  categoryCaption: { color: 'text.secondary' },
  title: { minHeight: 58, lineHeight: 1.3 },
  courseMetaIcon: { color: 'text.secondary', flexShrink: 0 },
  courseMetaText: { color: 'text.secondary', fontSize: '0.8125rem', lineHeight: 1.35 },
  metaRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    alignItems: 'center',
    width: 1,
    columnGap: 1,
  },
  metaCellStart: { justifySelf: 'start', minWidth: 0 },
  metaCellCenter: { justifySelf: 'center', minWidth: 0 },
  metaCellEnd: { justifySelf: 'end', minWidth: 0 },
  statusCaption: { color: 'text.secondary' },
  statusChip: {
    width: 'fit-content',
    textTransform: 'capitalize',
    transition: (theme) => theme.transitions.create(['background-color', 'color'], { duration: 220 }),
  },
  updatedCaption: { color: 'text.secondary' },
  updatedValue: { fontWeight: 600 },
  menuTrigger: {
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: 1,
  },
  menuPaper: {
    mt: 0.75,
    minWidth: { xs: 'min(calc(100vw - 24px), 320px)', sm: 220 },
    maxWidth: 'min(calc(100vw - 16px), 360px)',
    maxHeight: 'min(70dvh, 420px)',
    boxShadow: (theme) => theme.shadows[8],
  },
  menuItem: {
    py: 1,
    minHeight: { xs: 48, sm: 44 },
    borderRadius: 1,
    mx: 0.5,
    '& .MuiListItemIcon-root': { color: 'text.secondary' },
    '&:hover': {
      bgcolor: 'action.hover',
      '& .MuiListItemIcon-root': { color: 'primary.main' },
      '& .MuiTypography-root': { color: 'primary.main' },
    },
  },
};
