export const styles = {
  shell: { width: 1 },
  groupsStack: { width: 1 },
  loadingState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1.5,
    py: 8,
    borderRadius: 2,
    border: '1px dashed',
    borderColor: 'divider',
    bgcolor: 'background.neutral',
  },
  loadingText: { color: 'text.secondary' },
  emptyState: {
    p: { xs: 4, md: 5 },
    borderRadius: 2,
    border: '1px solid',
    borderColor: 'divider',
    bgcolor: 'background.neutral',
  },
  emptyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'background.paper',
    color: 'text.secondary',
    border: '1px solid',
    borderColor: 'divider',
  },
  emptyTitle: { fontWeight: 700 },
  emptyText: {
    color: 'text.secondary',
    maxWidth: 420,
    lineHeight: 1.6,
  },
  paginationBar: {
    px: { xs: 2, md: 2.5 },
    py: { xs: 2, md: 2.25 },
    borderRadius: 2,
    border: '1px solid',
    borderColor: 'divider',
    bgcolor: 'background.paper',
  },
};
