import {
  surfaceBackground,
  adaptiveSectionText,
  accentSectionBackground,
  adaptiveSectionMutedText,
  adaptiveSectionBackground,
} from '../shared/theme';

export const styles = {
  featureStrip: {
    root: { bgcolor: (theme) => accentSectionBackground(theme), color: 'common.white' },
    item: (isLast) => ({
      height: 1,
      px: 3,
      py: 3.5,
      alignItems: 'flex-start',
      borderBottom: { xs: '1px solid rgba(255,255,255,0.16)', lg: 'none' },
      borderRight: { xs: 'none', lg: isLast ? 'none' : '1px solid rgba(255,255,255,0.16)' },
    }),
    iconWrap: {
      width: 48,
      height: 48,
      flexShrink: 0,
      display: 'grid',
      placeItems: 'center',
      borderRadius: 2,
      bgcolor: 'rgba(255,255,255,0.14)',
    },
    title: { color: 'common.white' },
    description: { color: 'rgba(255,255,255,0.84)' },
  },
  value: {
    root: {
      bgcolor: (theme) => adaptiveSectionBackground(theme),
      color: (theme) => adaptiveSectionText(theme),
    },
    container: { py: { xs: 7, md: 10 } },
    heading: { maxWidth: 420, fontSize: { xs: '2rem', md: '3rem' }, lineHeight: 1.08, letterSpacing: '-0.03em' },
    copy: { maxWidth: 500, color: (theme) => adaptiveSectionMutedText(theme, 'rgba(255,255,255,0.72)'), lineHeight: 1.8 },
    pillar: { maxWidth: 320 },
    pillarTitle: (color) => ({ fontWeight: 700, color }),
    pillarDescription: { color: (theme) => adaptiveSectionMutedText(theme, 'rgba(255,255,255,0.68)'), lineHeight: 1.9 },
  },
  engineering: {
    root: { bgcolor: (theme) => surfaceBackground(theme) },
    container: { py: { xs: 8, md: 11 } },
    heading: { fontSize: { xs: '2rem', md: '3.2rem' }, lineHeight: 1.08, letterSpacing: '-0.03em' },
    subheading: { fontSize: { xs: '1.5rem', md: '2.1rem' } },
    copy: { maxWidth: 760, color: 'text.secondary', lineHeight: 1.9 },
    copySecondary: { maxWidth: 760, color: 'text.secondary', lineHeight: 1.85 },
    arrow: { mt: 0.5, color: 'primary.main', flexShrink: 0 },
    featureText: { color: 'text.secondary', lineHeight: 1.75 },
  },
  capabilities: {
    root: { bgcolor: (theme) => adaptiveSectionBackground(theme, 'subtle') },
    container: { py: { xs: 8, md: 11 } },
    header: { mb: { xs: 4, md: 6 }, textAlign: 'center' },
    heading: { fontSize: { xs: '2rem', md: '3rem' }, lineHeight: 1.08, letterSpacing: '-0.03em', color: (theme) => adaptiveSectionText(theme) },
    copy: { mx: 'auto', maxWidth: 840, color: (theme) => adaptiveSectionMutedText(theme, 'rgba(255,255,255,0.72)'), lineHeight: 1.9 },
    card: {
      height: 1,
      p: { xs: 3, md: 3.5 },
      borderRadius: 3,
      bgcolor: 'common.white',
      border: '1px solid',
      borderColor: 'divider',
      boxShadow: '0 18px 40px rgba(15, 23, 42, 0.06)',
      transition: 'transform 0.2s ease, box-shadow 0.2s ease',
      '&:hover': {
        transform: 'translateY(-4px)',
        boxShadow: '0 24px 50px rgba(15, 23, 42, 0.1)',
      },
    },
    cardIcon: {
      width: 56,
      height: 56,
      display: 'grid',
      placeItems: 'center',
      borderRadius: 2.5,
      bgcolor: 'rgba(98, 108, 255, 0.08)',
      color: 'primary.main',
    },
    cardTitle: { lineHeight: 1.35 },
    cardDescription: { color: 'text.secondary', lineHeight: 1.8 },
  },
};
