export const styles = {
  card: {
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: 2,
    boxShadow: 'none',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: { xs: 'flex-start', sm: 'center' },
    justifyContent: 'space-between',
    gap: 1.5,
    flexWrap: 'wrap',
    px: { xs: 2, md: 2.75 },
    py: { xs: 1.5, md: 1.75 },
    bgcolor: 'background.neutral',
    borderBottom: '1px solid',
    borderColor: 'divider',
  },
  headerMain: { minWidth: 0, flex: '1 1 auto' },
  headerIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 1.25,
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
    bgcolor: 'background.paper',
    color: 'primary.main',
    border: '1px solid',
    borderColor: 'divider',
  },
  headerText: { minWidth: 0 },
  courseCaption: {
    color: 'text.secondary',
    fontWeight: 600,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    fontSize: 10,
    lineHeight: 1.2,
  },
  courseTitle: {
    fontWeight: 700,
    lineHeight: 1.35,
    fontSize: { xs: '0.98rem', md: '1.02rem' },
  },
  countChip: {
    fontWeight: 600,
    height: 26,
    flexShrink: 0,
  },
  cardContent: {
    px: { xs: 2, md: 2.75 },
    py: { xs: 0.5, md: 0.75 },
    '&:last-child': { pb: { xs: 1.5, md: 1.75 } },
  },
  rowsStack: { minWidth: 0 },
};
