export const ENROLLMENT_SUBMIT_REQUEST = 'lms/ENROLLMENT_SUBMIT_REQUEST';
export const ENROLLMENT_SUBMIT_SUCCESS = 'lms/ENROLLMENT_SUBMIT_SUCCESS';
export const ENROLLMENT_SUBMIT_FAILURE = 'lms/ENROLLMENT_SUBMIT_FAILURE';

export const QUIZ_SIMULATION_REQUEST = 'lms/QUIZ_SIMULATION_REQUEST';
export const QUIZ_SIMULATION_SUCCESS = 'lms/QUIZ_SIMULATION_SUCCESS';
export const QUIZ_SIMULATION_FAILURE = 'lms/QUIZ_SIMULATION_FAILURE';
export const QUIZ_QUESTION_SET_REQUEST = 'lms/QUIZ_QUESTION_SET_REQUEST';
export const QUIZ_QUESTION_SET_SUCCESS = 'lms/QUIZ_QUESTION_SET_SUCCESS';
export const QUIZ_QUESTION_SET_FAILURE = 'lms/QUIZ_QUESTION_SET_FAILURE';

export const ADMIN_TOGGLE_MODULE_VISIBILITY_REQUEST =
  'lms/ADMIN_TOGGLE_MODULE_VISIBILITY_REQUEST';
export const ADMIN_TOGGLE_MODULE_VISIBILITY_SUCCESS =
  'lms/ADMIN_TOGGLE_MODULE_VISIBILITY_SUCCESS';
export const ADMIN_TOGGLE_MODULE_VISIBILITY_FAILURE =
  'lms/ADMIN_TOGGLE_MODULE_VISIBILITY_FAILURE';

export const ADMIN_UPLOAD_MODULE_REQUEST = 'lms/ADMIN_UPLOAD_MODULE_REQUEST';
export const ADMIN_UPLOAD_MODULE_SUCCESS = 'lms/ADMIN_UPLOAD_MODULE_SUCCESS';
export const ADMIN_UPLOAD_MODULE_FAILURE = 'lms/ADMIN_UPLOAD_MODULE_FAILURE';

export const ADMIN_UPDATE_ENROLLMENT_STATUS_REQUEST =
  'lms/ADMIN_UPDATE_ENROLLMENT_STATUS_REQUEST';
export const ADMIN_UPDATE_ENROLLMENT_STATUS_SUCCESS =
  'lms/ADMIN_UPDATE_ENROLLMENT_STATUS_SUCCESS';
export const ADMIN_UPDATE_ENROLLMENT_STATUS_FAILURE =
  'lms/ADMIN_UPDATE_ENROLLMENT_STATUS_FAILURE';

export const LMS_FLASH_SET = 'lms/LMS_FLASH_SET';
export const LMS_FLASH_CLEAR = 'lms/LMS_FLASH_CLEAR';

export const LMS_RESOURCE_FETCH_REQUEST = 'lms/LMS_RESOURCE_FETCH_REQUEST';
export const LMS_RESOURCE_FETCH_SUCCESS = 'lms/LMS_RESOURCE_FETCH_SUCCESS';
export const LMS_RESOURCE_FETCH_FAILURE = 'lms/LMS_RESOURCE_FETCH_FAILURE';

export const LMS_COMMAND_REQUEST = 'lms/LMS_COMMAND_REQUEST';
export const LMS_COMMAND_SUCCESS = 'lms/LMS_COMMAND_SUCCESS';
export const LMS_COMMAND_FAILURE = 'lms/LMS_COMMAND_FAILURE';
